

POST http://localhost:3000/patient
Content-Type: application/json

  {
    "name": "Mariana Duarte",
    "description": "Paciente com bom progresso terapêutico.",
    "questionarios": ["2", "5"]
  
  }
###
POST http://localhost:3000/patient/2/add-questionario
Content-Type: application/json

{
  "questionario_key": "1"
}

###
GET http://localhost:3000/patient
###
GET http://localhost:3000/patient/1

###
GET http://localhost:3000/patient/1/questionarios
//TENTAR CRIAR OU CORRIGIR (SEGUINDO A ESTRUTURA)
###
GET http://localhost:3000/patient/1/Questionario?status=1


###
GET http://localhost:3000/patient/1/Questionario


###
GET http://localhost:3000/patient/key/1/level/1
