
GET http://localhost:3000/questionnaire
###
GET http://localhost:3000/Questionnaire
###
POST http://localhost:3000/Questionnaire
Content-Type: application/json

{
    "name":"Questionario semanal",
    "Person:_key":"1",
    "Questionario":"psicotécnico",
    "status":"3" 
    
}


###
GET http://localhost:3000/questionnaire/1

###

GET http://localhost:3000/questionnaire/4/questions


###
GET http://localhost:3000/questionnaire/

###
GET http://localhost:3000/questionnaire/person/1

###
GET http://localhost:3000/questionnaire/6/pacientes
###
PUT http://localhost:3000/questionnaire/14/person/1

###
GET http://localhost:3000/questionnaire/14/person/1

###
GET http://localhost:3000/questionnaire/14/person/1

###
GET http://localhost:3000/questionnaire?sort=_key&order=desc